#! /usr/bin/python3

import time
import random
  
def parryprinter(t, i):
    
    while t:
        timer = '{}'.format(random.randint(1,9))
        print(f'\r{timer}', end='')
        time.sleep(int(i))
        t -= 1
    print('\n\nGood job!!')
  
  
t = input("Enter the amount of repetitions: ")
i = input("Enter the intervals in seconds: ")
  

if __name__ == "__main__":
    parryprinter(int(t), int(i))
